---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
    update_cache: yes

- name: Start and Enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Move Nginx Conf to Server
  template:
    src: files/app.j2
    dest: /etc/nginx/sites-available/app
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0644'

- name: Create symlink
  shell: sudo ln -s /etc/nginx/sites-available/app /etc/nginx/sites-enabled/

- name: Serve Web Page
  ansible.builtin.template:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'
  notify: Reload Nginx